### ISSUE TITLE
Category Description not displaying

### ISSUE THREAD

**Issue by TectonicKestrel** [StockChannel/SinchImport#16]
Using Magento 2.4.3-p2, but this has been an issue since i started using this module.
The category description does not show in the admin panel or in the frontend, but does appear in the database in the catalog_category_entity_varchar table.
Im using the porto theme, but doing a var_dump of $_description = $block->getCurrentCategory()->getDescription() which is the magento code to display the description returns "NULL".
var_dump($this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute($block->getCurrentCategory(), $_description, 'description')); also returns "NULL"
Is this the same reason that the admin panel doesnt show the description and this data isnt inserted into the database correctly?
The meta title seems to work, but the description or meta description do not.

There is a separate issue of the category image not displaying either, which i have created a temporary workaround for myself, but was told this would be fixed quite a while ago but it hasnt been

**Comment by nicka101** [comment]
Should be resolved as of 3.6.1
