### ISSUE TITLE
How to install？

### ISSUE THREAD

**Issue by sanker2008** [StockChannel/SinchImport#2]
I download the file and put it into magentoroot/app/code/SITC    
run php bin/magento setup:upgrade
get error:
Updating modules:
Plugin class SITC\Sinchimport\Plugin\Catalog\Model\Indexer\Product\Flat\FlatTableBuilder doesn't exist

**Comment by nicka101** [comment]
The supported way to install this extension is via composer, i.e. by running
`composer require stockinthechannel/import` from the Magento base directory

**Comment by nicka101** [comment]
For more details, see [the wiki on installing](https://github.com/StockChannel/SinchImport/wiki/Installing)
