### ISSUE TITLE
Magento 2.3 Table compatibility

### ISSUE THREAD

**Issue by nicka101** [StockChannel/SinchImport#6]
Running setup:upgrade on 2.3.x results in "Cannot process definition to array for type enum" due to the enum columns on sinch_import_status_statistic

**Comment by loibv5989** [comment]
please merge commit branch feature/tigren. (fixed c88fdc8)

**Comment by nicka101** [comment]
The issue is not fixed by c88fdc8 as it only changes 1 of the enum columns on the table (there are 2). Issue has been resolved by e3dd8e9
